// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjbvpw1MxAMoqidQP209m2ABaoLvc17o',
    appId: '1:743919580047:web:d59f33c75f326bb89851fa',
    messagingSenderId: '743919580047',
    projectId: 'ods-3-cf4c7',
    authDomain: 'ods-3-cf4c7.firebaseapp.com',
    storageBucket: 'ods-3-cf4c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAX66CiOfWIcV9M1BYAcAGev88FyUSoU',
    appId: '1:743919580047:android:6543ab776986c4929851fa',
    messagingSenderId: '743919580047',
    projectId: 'ods-3-cf4c7',
    storageBucket: 'ods-3-cf4c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ps3BFIhWBFf2NZZIo6bcy7X6twrNh48',
    appId: '1:743919580047:ios:146aab654d8a5c169851fa',
    messagingSenderId: '743919580047',
    projectId: 'ods-3-cf4c7',
    storageBucket: 'ods-3-cf4c7.firebasestorage.app',
    iosBundleId: 'com.vsd.ods3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Ps3BFIhWBFf2NZZIo6bcy7X6twrNh48',
    appId: '1:743919580047:ios:aa0b6aac6d9d9fc29851fa',
    messagingSenderId: '743919580047',
    projectId: 'ods-3-cf4c7',
    storageBucket: 'ods-3-cf4c7.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLjbvpw1MxAMoqidQP209m2ABaoLvc17o',
    appId: '1:743919580047:web:4e1d51a336db81b79851fa',
    messagingSenderId: '743919580047',
    projectId: 'ods-3-cf4c7',
    authDomain: 'ods-3-cf4c7.firebaseapp.com',
    storageBucket: 'ods-3-cf4c7.firebasestorage.app',
  );
}
